#!/bin/bash
#
# Script to configure rsyslog to send logs to a remote syslog server
# Author: Darren Soothill
# Usage: sudo ./configure_remote_syslog.sh
#

set -e

# Configuration variables
SYSLOG_SERVER="syslog"
SYSLOG_PORT="514"
PROTOCOL="udp"  # Options: udp, tcp
CONFIG_FILE="/etc/rsyslog.d/50-remote-syslog.conf"
BACKUP_SUFFIX=".backup.$(date +%Y%m%d_%H%M%S)"

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root (use sudo)"
   exit 1
fi

# Display configuration
echo "================================================"
echo "Remote Syslog Configuration Script"
echo "================================================"
echo "Syslog Server: $SYSLOG_SERVER"
echo "Port: $SYSLOG_PORT"
echo "Protocol: $PROTOCOL"
echo "Config File: $CONFIG_FILE"
echo "================================================"
echo ""

# Prompt for confirmation
read -p "Do you want to proceed with this configuration? (y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    print_warn "Configuration cancelled by user"
    exit 0
fi

# Check if rsyslog is installed
if ! command -v rsyslogd &> /dev/null; then
    print_error "rsyslog is not installed"
    print_info "Installing rsyslog..."
    
    # Detect package manager and install
    if command -v apt-get &> /dev/null; then
        apt-get update && apt-get install -y rsyslog
    elif command -v yum &> /dev/null; then
        yum install -y rsyslog
    elif command -v zypper &> /dev/null; then
        zypper install -y rsyslog
    elif command -v dnf &> /dev/null; then
        dnf install -y rsyslog
    else
        print_error "Could not detect package manager. Please install rsyslog manually."
        exit 1
    fi
fi

# Backup existing config if it exists
if [[ -f "$CONFIG_FILE" ]]; then
    print_info "Backing up existing configuration to ${CONFIG_FILE}${BACKUP_SUFFIX}"
    cp "$CONFIG_FILE" "${CONFIG_FILE}${BACKUP_SUFFIX}"
fi

# Create the rsyslog configuration
print_info "Creating rsyslog configuration..."

cat > "$CONFIG_FILE" << EOF
# Remote syslog configuration
# Generated by configure_remote_syslog.sh on $(date)
# Send all logs to remote syslog server: $SYSLOG_SERVER

# Queue configuration for reliability
\$ActionQueueType LinkedList   # use asynchronous processing
\$ActionQueueFileName srvrfwd  # set file name, also enables disk mode
\$ActionResumeRetryCount -1    # infinite retries on insert failure
\$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down

# Send all logs to remote syslog server
EOF

# Add protocol-specific configuration
if [[ "$PROTOCOL" == "tcp" ]]; then
    echo "*.* @@${SYSLOG_SERVER}:${SYSLOG_PORT}" >> "$CONFIG_FILE"
    print_info "Configured for TCP protocol (reliable)"
else
    echo "*.* @${SYSLOG_SERVER}:${SYSLOG_PORT}" >> "$CONFIG_FILE"
    print_info "Configured for UDP protocol (standard)"
fi

# Add optional facility-specific forwarding examples (commented out)
cat >> "$CONFIG_FILE" << 'EOF'

# Optional: Forward specific facilities only (uncomment as needed)
# kern.*     @syslog:514   # Kernel messages
# auth.*     @syslog:514   # Authentication messages
# mail.*     @syslog:514   # Mail system messages
# cron.*     @syslog:514   # Cron messages
# daemon.*   @syslog:514   # Daemon messages

# Optional: Exclude certain logs from being sent remotely
# :msg, contains, "keyword to exclude" stop
EOF

print_info "Configuration file created: $CONFIG_FILE"

# Test configuration syntax
print_info "Testing rsyslog configuration syntax..."
if rsyslogd -N1 &> /dev/null; then
    print_info "Configuration syntax is valid"
else
    print_error "Configuration syntax check failed"
    rsyslogd -N1
    exit 1
fi

# Test connectivity to syslog server
print_info "Testing connectivity to syslog server..."

# Try to resolve the hostname
if host "$SYSLOG_SERVER" &> /dev/null || getent hosts "$SYSLOG_SERVER" &> /dev/null; then
    print_info "Successfully resolved hostname: $SYSLOG_SERVER"
    
    # Get IP address
    SYSLOG_IP=$(getent hosts "$SYSLOG_SERVER" | awk '{ print $1 }' | head -n1)
    print_info "Resolved to IP: $SYSLOG_IP"
    
    # Test port connectivity
    if command -v nc &> /dev/null; then
        if [[ "$PROTOCOL" == "tcp" ]]; then
            if timeout 5 nc -zv "$SYSLOG_SERVER" "$SYSLOG_PORT" 2>&1 | grep -q succeeded; then
                print_info "TCP connection to ${SYSLOG_SERVER}:${SYSLOG_PORT} successful"
            else
                print_warn "Could not connect to ${SYSLOG_SERVER}:${SYSLOG_PORT} via TCP"
                print_warn "Firewall or service may not be ready"
            fi
        else
            # UDP test is less reliable
            print_warn "UDP connectivity test is not reliable with netcat"
        fi
    else
        print_warn "netcat (nc) not found, skipping port connectivity test"
    fi
else
    print_error "Could not resolve hostname: $SYSLOG_SERVER"
    print_warn "Make sure the syslog server is reachable via DNS or /etc/hosts"
    print_warn "For Tailscale, ensure MagicDNS is enabled"
    echo ""
    read -p "Do you want to continue anyway? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_warn "Configuration cancelled"
        exit 1
    fi
fi

# Restart rsyslog service
print_info "Restarting rsyslog service..."
if systemctl restart rsyslog; then
    print_info "rsyslog service restarted successfully"
else
    print_error "Failed to restart rsyslog service"
    exit 1
fi

# Check service status
if systemctl is-active --quiet rsyslog; then
    print_info "rsyslog service is running"
else
    print_error "rsyslog service is not running"
    systemctl status rsyslog
    exit 1
fi

# Send test message
print_info "Sending test log message..."
logger -t "remote_syslog_test" "Test message from $(hostname) - Configuration completed successfully at $(date)"

# Display summary
echo ""
echo "================================================"
echo "Configuration Summary"
echo "================================================"
echo "✓ Configuration file created: $CONFIG_FILE"
echo "✓ rsyslog service restarted"
echo "✓ Test message sent to remote syslog server"
echo ""
echo "Next steps:"
echo "1. Check the remote syslog server to verify logs are being received"
echo "2. Monitor local logs: sudo tail -f /var/log/messages (or /var/log/syslog)"
echo "3. Check rsyslog status: sudo systemctl status rsyslog"
echo "4. View rsyslog errors: sudo journalctl -u rsyslog -f"
echo ""
echo "To modify configuration, edit: $CONFIG_FILE"
echo "To disable remote logging, run: sudo rm $CONFIG_FILE && sudo systemctl restart rsyslog"
echo "================================================"

print_info "Configuration completed successfully!"

exit 0
